oop5 finish notification
js-tasks-ru/js-20221021_elenergetica87 pull request #5
Opened 2022-11-06 13:14 UTC by sergrage

этот тест какой-то странный. не работал, пока я не убрал строчку element = element.firstElementChild;
почему-то если я создаю э-т сам, то эта строчка нужна, если его передают в метод show, то нет(

  it('should have ability to define target element for rendering', () => {
    notificationMessage = new NotificationMessage('hi');
    const div = document.createElement('div');

    notificationMessage.show(div);

    expect(div).toContainHTML(notificationMessage.element.outerHTML);
  });

2022-11-06 13:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-06 15:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-06 15:48 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-06 16:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-11-06 16:22 UTC, sergrage commented
вторая задача вообще лютая) 
все работает, но смущает то, как я проверял на наличие шаблона в методе getBodyTemplate(). Посмотрите, есть варианты упростить?

2022-11-07 14:12 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.text = text || 'hi';
что такое `hi`? почему это используется в качестве значения по умолчанию

2022-11-07 14:13 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.duration = (props && props.duration) || 1000;
значения по умолчанию лучше задать сразу в аргументах

2022-11-07 14:14 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show(element) {
тут следует задать для `element` значение по умолчанию:
```
show(element = document.body)
```

2022-11-07 14:14 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  initEventListeners() {
этот метод тут не нужен!

2022-11-07 14:14 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
>  export default class NotificationMessage {
а где удаление предыдущего нотификейшена?

2022-11-07 14:15 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +      let arrow = item.sortable ? arrowTemplate : '';
может `const`?

2022-11-07 14:15 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    const ids = this.headerConfig.map(x => x.id);
проверьте исопльзование `let/const`

2022-11-07 14:16 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        let headerItem = this.headerConfig.find(x => x.id === id);
не именуйте аргументы одним символом

2022-11-07 14:17 UTC, dosandk requested changes
SortableTable - good 👍
в нотификейшене следует добавить проверку, согласно к-й предыдущий нотификейшен будет удален со страницы

2022-11-07 15:18 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-07 15:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-11-07 16:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-11-08 13:39 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    NotificationMessage.allInstances.push(this);
👍 good 
подумайте может не массив тут нужен, нам ведь нужна только ссылка на предыдущий нотификейшен

2022-11-08 13:39 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (NotificationMessage.allInstances) {
👍 good

2022-11-08 13:39 UTC, dosandk approved these changes
👍 good

2022-11-08 13:40 UTC, merged