oop-6
js-tasks-ru/js-20221021_elenergetica87 pull request #6
Opened 2022-11-10 07:35 UTC by sergrage

2022-11-10 07:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-10 09:45 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-11 14:41 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    // const body = document.createElement("div");
не оставляйте закомментированный код

2022-11-11 14:41 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements.header.addEventListener('pointerdown', this.sortClick);
👍 good 
лайк за `event-delegation` подход

2022-11-11 14:41 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +  sortClick = (event) => {
👍 good

2022-11-11 14:41 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  constructor() {
👍 good

2022-11-11 14:42 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  pointerover = e => {
не экономьте на именах переменных

2022-11-11 14:42 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    this.remove();
а где удаление обработчиков?

2022-11-11 14:43 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.removeEventListener('pointermove', this.pointerover);
почему событие называется `pointermove` а метод `pointerover`?

2022-11-11 14:43 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      el.addEventListener('pointerout', this.onmouseout);
почему имя метод и имя события разные?

2022-11-11 14:43 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      console.log(e.clientX, e.clientY);
почему `console` оставили в PR?

2022-11-11 14:44 UTC, dosandk requested changes
решение `Tooltip` следует поправить

2022-11-11 16:06 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-13 14:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-11-13 17:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-14 10:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-14 14:38 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  static _instance;
👍 good лайк за статическое свойство

2022-11-14 14:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.removeEventListener('pointermove', this.onPointerMove);
👍 good

2022-11-14 14:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    this.element.style.left = 10 + event.clientX + 'px';
10 следует вынести в переменную

2022-11-14 14:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.removeEventListener('pointerover', this.onPointerOver);
👍 good

2022-11-14 14:46 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    const url = BACKEND_URL + '/' + this.url + `?from=${start}&to=${end}`;
обратите внимание на `new URL`

2022-11-14 14:47 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    fetchJson(url).then(res => {
старайтесь отдавать предпочтение `async/await`

2022-11-14 14:48 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    fetchJson(url).then(res => {
не забывайте обрабатывать ошибки в асинхронном коде

2022-11-14 14:49 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    // const loadDataButton = document.getElementById('loadOrders');
а зачем этот метод?
почему он пустой?

2022-11-14 14:50 UTC, dosandk approved these changes
👍 good лайк за загрузку данных с бекенда

2022-11-14 14:51 UTC, merged